package md.ramaiana.foodmarket.controller.dto.common;

public enum ErrorCode {
    OK,
    CLIENT_NOT_FOUND,
    CLIENT_BLOCKED,
    GOOD_NOT_FOUND,
    EMAIL_EXISTS,
    EMAIL_EMPTY,
    PASSWORD_EMPTY,
    QUANTITY_IS_LESS_OR_EQUAL_TO_ZERO,
    GOOD_ID_IS_LESS_OR_EQUAL_TO_ZERO,
    ORDER_NOT_FOUND,
    ORDER_ID_IS_ZERO,
    ORDER_ID_IS_NULL,
    PAGE_IS_LESS_OR_EQUAL_TO_ZERO,
    PAGE_SIZE_IS_LESS_OR_EQUAL_TO_ZERO,
    ORDER_ALREADY_PROCESSED,
    INTERNAL_SERVER_ERROR
}
