CREATE TABLE IF NOT EXISTS client
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36)  NOT NULL,
    name       TEXT         NOT NULL,
    idno       VARCHAR(13)  NOT NULL UNIQUE,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS brand
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid     VARCHAR(36) NOT NULL,
    name     TEXT        NOT NULL,
    erp_code TEXT        NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS product_group
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            VARCHAR(36) NOT NULL,
    name            TEXT        NOT NULL,
    parent_group_id INTEGER REFERENCES product_group (id),
    erp_code        TEXT UNIQUE,
    created_at      TIMESTAMP   NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMP,
    updated_at      TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product
(
    id         INT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36)  NOT NULL,
    name       TEXT         NOT NULL,
    price      NUMERIC      NOT NULL DEFAULT 0,
    brand_id   INTEGER REFERENCES brand (id),
    group_id   INTEGER REFERENCES product_group (id),
    unit       TEXT,
    package    NUMERIC,
    erp_code   TEXT,
    bar_code   TEXT,
    weight     NUMERIC,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_user
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    email      TEXT        NOT NULL UNIQUE,
    passwd     TEXT        NOT NULL,
    client_id  INTEGER REFERENCES client (id),
    created_at TIMESTAMP   NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_user_roles
(
    user_id INTEGER NOT NULL REFERENCES app_user (id),
    role    TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS "order"
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid              VARCHAR(36) NOT NULL,
    client_id         INTEGER REFERENCES client (id),
    total_sum         NUMERIC     NOT NULL DEFAULT 0,
    created_at        TIMESTAMP   NOT NULL DEFAULT NOW(),
    deleted_at        TIMESTAMP,
    processed_at      TIMESTAMP,
    processing_result TEXT,
    status            TEXT        NOT NULL DEFAULT 'NEW'
);

CREATE TABLE IF NOT EXISTS order_product
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    order_id   INTEGER     NOT NULL REFERENCES "order" (id),
    product_id INTEGER     NOT NULL REFERENCES product (id),
    quantity   NUMERIC     NOT NULL DEFAULT 0,
    price      NUMERIC     NOT NULL DEFAULT 0,
    sum        NUMERIC     NOT NULL DEFAULT 0,
    weight     NUMERIC     NOT NULL DEFAULT 0
);
