CREATE TABLE IF NOT EXISTS client
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    idno       VARCHAR(13) NOT NULL UNIQUE,
    email      TEXT,
    created_at TIMESTAMP   NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS client_phones
(
    number    TEXT    NOT NULL,
    name      TEXT,
    client_id INTEGER NOT NULL REFERENCES client (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS client_addresses
(
    type         TEXT NOT NULL,
    full_address TEXT,
    description  TEXT,
    client_id    INTEGER REFERENCES client (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS brand
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    erp_code   TEXT        NOT NULL UNIQUE,
    created_at TIMESTAMP   NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_group
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT        NOT NULL,
    parent_group_id INTEGER REFERENCES product_group (id),
    erp_code        TEXT UNIQUE,
    created_at      TIMESTAMP   NOT NULL,
    deleted_at      TIMESTAMP,
    updated_at      TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    brand_id   INTEGER REFERENCES brand (id),
    group_id   INTEGER REFERENCES product_group (id),
    unit       TEXT,
    package    NUMERIC     not null,
    erp_code   TEXT        not null,
    bar_code   TEXT,
    weight     NUMERIC,
    created_at TIMESTAMP   NOT NULL,
    deleted_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_user
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      TEXT        NOT NULL UNIQUE,
    passwd     TEXT        NOT NULL,
    client_id  INTEGER REFERENCES client (id),
    created_at TIMESTAMP   NOT NULL
);

CREATE TABLE IF NOT EXISTS app_user_roles
(
    user_id INTEGER NOT NULL REFERENCES app_user (id),
    role    TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS "order"
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id         INTEGER     not null REFERENCES client (id),
    total_sum         NUMERIC     not null,
    created_at        TIMESTAMP   not null,
    deleted_at        TIMESTAMP,
    processed_at      TIMESTAMP,
    processing_result TEXT,
    status            TEXT        NOT NULL
);

CREATE TABLE IF NOT EXISTS order_product
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   INTEGER     NOT NULL REFERENCES "order" (id),
    product_id INTEGER     NOT NULL REFERENCES product (id),
    quantity   NUMERIC     NOT NULL,
    price      NUMERIC     NOT NULL,
    sum        NUMERIC     NOT NULL,
    weight     NUMERIC     NOT NULL
);

CREATE TABLE IF NOT EXISTS storages
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     text not null,
    erp_code text not null
);

CREATE TABLE IF NOT EXISTS prices
(
    "type"     text    not null,
    product_id int
        constraint prices_product_id_fk
            references product
                on delete cascade,
    storage_id int
        constraint prices_storages_id_fk
            references storages,
    price      numeric not null
);

create index if not exists prices_type_storage_id_product_id_index
    on prices ("type", storage_id, product_id);

CREATE TABLE IF NOT EXISTS balances
(
    storage_id int
        constraint balances_storages_id_fk
            references storages
                on delete cascade,
    product_id int
        constraint balances_product_id_fk
            references product
                on delete cascade,
    quantity   numeric not null
);

create unique index if not exists balances_product_id_storage_id_uindex
    on balances (product_id, storage_id);
